### ISSUE TITLE
Get_visibility / get_visibility_prefix out of bounds error

### ISSUE THREAD

**Issue by phpsystems** [guedou/bam#1]
Hi,

   Since the "ret" array is defined to be 16 elements in size, any time more elements are attempted to be the added, the scripts fail with the following:

Traceback (most recent call last):
  File "/usr/share/pyshared/flask/app.py", line 1518, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/share/pyshared/flask/app.py", line 1506, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/share/pyshared/flask/app.py", line 1504, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1264, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/share/pyshared/flask/app.py", line 1262, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/pyshared/flask/app.py", line 1248, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/bam.py", line 29, in flask_index
    return lib.www.pages.index(app.config["CONFIG"])
  File "/vagrant/lib/www/pages.py", line 104, in index
    rendered_map_collectors = map_collectors(config, "dynamic", wrapper=False)
  File "/vagrant/lib/www/pages.py", line 57, in map_collectors
    collectors = filter(lambda p: p != None, get_visibility(asn))
  File "/vagrant/lib/tools/get_visibility.py", line 51, in get_visibility
    ret[rrc_id] = doc

Simply changing : 
ret = [None] \* 16
to
ret = [None] \* 32

in both files fixes the issue in the short term. Possibly better to dynamically assign the size?

**Comment by guedou** [comment]
Thanks a lot for the report ! I did not know that bam was still used.

It is now fixed.
